# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-21 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaimWheel',
            new_name='MainWheel',
        ),
    ]
